add_newline = true

format = """
$username@$hostname:$directory$git_branch
$character
"""

[username]
style_user = "bold green"
show_always = true

[hostname]
style = "bold blue"

[directory]
style = "bold purple"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ğŸŒ± "
style = "bold yellow"

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
