add_newline = true

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username@$hostname:$directory$git_branch
$character
"""

[username]
style_user = "bold green"
show_always = true

[hostname]
style = "bold blue"

[directory]
style = "bold purple"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ðŸŒ± "
style = "bold yellow"

[character]
success_symbol = "[âžœ](green)"
error_symbol = "[âžœ](red)"
